------Practica 11
-----1. Total de discos publicados por cada país---
SELECT * FROM DISCO WHERE ORIGEN_DISQUERA='Colombia';

SELECT ORIGEN_DISQUERA AS PAIS, COUNT(NUMREF) AS Total_Discos
FROM DISCO
GROUP BY ORIGEN_DISQUERA;


---2. Número de canciones por genero-----

SELECT GENERO, COUNT(CODCAN) AS Total_CANCION
FROM DISCO NATURAL INNER JOIN ESTA NATURAL INNER JOIN CANCION
GROUP BY GENERO;


/*3. Obtener las canciones que tienen el mismo titulo pero que fueron escritas
por diferente compositor*/

SELECT TITULO, COUNT(CURPC) AS NUM_COMPOSITOR
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY TITULO;

---Sleccionar los que tenan mas de un num_compositor---


SELECT TITULO, COUNT(CURPC) AS NUM_COMPOSITOR
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY TITULO
HAVING COUNT(CURPC) > 1;

/*4. Obtener nombre del compositor y numero de canciones escritas por los
compositores Mexicanos y Españoles*/

select Nacionalidad, NOMBREC, NUM_CANCIONES
FROM COMPOSITOR NATURAL INNER JOIN 
(
SELECT CURPC, COUNT(COD) AS NUM_CANCIONES
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY CURPC
)
WHERE NACIONALIDAD like 'M%co' OR NACIONALIDAD like 'Es%';

/* Obtener nombre de las canciones y su compositor que duran mas de 3
minutos cuyo compositor haya escrito mas de 3 canciones.*/
--- Obtener canciones con duracionmayor a tres minuts---
SELECT *
FROM CANCION NATURAL INNER JOIN COMPOSITOR
WHERE DURACION > '03:00';

----Obtener compositor haya escrito mas de 3 canciones.----
SELECT NOMBREC, COUNT(COD) AS NUM_CANCIONES
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY NOMBREC
HAVING(COUNT(COD)>3);


----consulta competa----
SELECT NOMBREC, TITULO
FROM CANCION NATURAL INNER JOIN (
SELECT NOMBREC, COUNT(COD) AS NUM_CANCIONES
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY NOMBREC
HAVING(COUNT(COD)>3)
)
WHERE DURACION > '03:00';



/*Obtener el nombre de los discos que tienen mas de un compositor.*/

SELECT ALBUM, COUNT(CURPC) AS NumcOMP
FROM ESTA NATURAL INNER JOIN CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY ALBUM
HAVING COUNT(CURPC) >1;



/*Obtener los artistas que pertenecen a una sola disquera*/
SELECT NOMBRE, COUNT(disquera) AS NumDisq
FROM ARTISTA NATURAL INNER JOIN PERTENECE NATURAL INNER JOIN INTERPRETE NATURAL INNER JOIN DISCO
GROUP BY NOMBRE
HAVING COUNT(disquera) =1;



/*  Disqueras que han grabado menos de 5 canciones con una duración mayor
a 5 minutos     */

SELECT DISQUERA, COUNT(CODCAN) AS NumCan
FROM ( SELECT * FROM CANCION WHERE DURACION > '05:00') NATURAL INNER JOIN ESTA NATURAL INNER JOIN DISCO NATURAL INNER JOIN DISQUERA
GROUP BY DISQUERA
HAVING COUNT(CODCAN) < 5;


/*Nombres de artistas que tengan mas de dos clubs*/

SELECT NOMBRE, COUNT(NOMBRECLUB) AS NumCLUB
FROM ARTISTA NATURAL INNER JOIN PERTENECE NATURAL INNER JOIN INTERPRETE NATURAL INNER JOIN CLUB
GROUP BY NOMBRE
HAVING COUNT(NOMBRECLUB) >1 ;---LA DEJE EN 1 POR QUE NO HAY MAYORES A 2 EN LA BASE---


/*Artistas que hayan grabado al menos 2 albumnes con mas de 8 canciones
cada album.*/
SELECT NOMBRE, COUNT(ALBUM) AS NumALBUM
FROM ARTISTA NATURAL INNER JOIN PERTENECE NATURAL INNER JOIN INTERPRETE 
NATURAL INNER JOIN 

(SELECT ALBUM, COUNT(CODCAN) 
FROM DISCO NATURAL INNER JOIN ESTA NATURAL INNER JOIN CANCION 
GROUP BY ALBUM
HAVING COUNT(CODCAN)>8 )

GROUP BY NOMBRE
HAVING COUNT(ALBUM) >1 ;

