CREATE TABLE  ARTISTA (
    CURP  VARCHAR(20) NOT NULL,
    NOMBRE  VARCHAR(50) NOT NULL
);

 

CREATE TABLE  CANCION (
    CODCAN INTEGER NOT NULL,
    TITULO  VARCHAR(60) NOT NULL,
    DURACION  VARCHAR(10),
    CURPC  VARCHAR(20)
);
 
CREATE TABLE  CLUB (
    NOMBRECLUB  VARCHAR(30) NOT NULL,
    LUGARORIGEN  VARCHAR(30) NOT NULL,
    NUMFANS INTEGER,
    TELEFONO  VARCHAR(30),
    NOMBREINT  VARCHAR(50)
);

 

CREATE TABLE  COMPOSITOR (
    CURPC  VARCHAR(20) NOT NULL,
    NOMBREC  VARCHAR(50),
    NACIONALIDAD  VARCHAR(50)
);

 

CREATE TABLE  DISCO (
    NUMREF INTEGER NOT NULL,
    ALBUM  VARCHAR(50) NOT NULL,
    GENERO  VARCHAR(40),
    FECHAL VARCHAR(50),
    DISQUERA  VARCHAR(50),
    ORIGEN_DISQUERA  VARCHAR(50),
    NOMBREINT  VARCHAR(50)
);
 
CREATE TABLE  DISQUERA (
    DISQUERA  VARCHAR(30) NOT NULL,
    ORIGEN_DISQUERA  VARCHAR(30) NOT NULL,
    DIRECCION  VARCHAR(50),
    TELEFONO  VARCHAR(20)
);
 

CREATE TABLE  ESTA (
    CODCAN INTEGER NOT NULL,
    NUMREF INTEGER,
    ALBUM  VARCHAR(50)
);

 

CREATE TABLE  INTERPRETE (
    FECHACREACION varchar(50),
    NOMBREINT  VARCHAR(50) NOT NULL,
    PAIS  VARCHAR(50)
);

--DROP TABLE INTERPRETE;
--DROP TABLE CLUB;

CREATE TABLE  PERTENECE (
    CURP VARCHAR(50) NOT NULL,
    FUNCION  VARCHAR(30),
    NOMBREINT  VARCHAR(50)
);

ALTER TABLE     ARTISTA
ADD CONSTRAINT PK_ARTISTA 
PRIMARY KEY (CURP);



ALTER TABLE     CANCION
ADD CONSTRAINT PK_CANCION
PRIMARY KEY (COD);



ALTER TABLE     CLUB
ADD CONSTRAINT PK_CLUB 
PRIMARY KEY (NOMBRECLUB, LUGARORIGEN);

 

ALTER TABLE     COMPOSITOR
ADD CONSTRAINT  PK_COMPOSITOR
 PRIMARY KEY ( CURPC );

 

ALTER TABLE     DISCO
ADD CONSTRAINT PK_DISCO 
PRIMARY KEY ( NUMREF , ALBUM);

 

ALTER TABLE     DISQUERA
ADD CONSTRAINT  PK_DISQUERA 
PRIMARY KEY ( DISQUERA, ORIGEN_DISQUERA);


 

ALTER TABLE     INTERPRETE
ADD CONSTRAINT  PK_INTERPRETE  
PRIMARY KEY ( NOMBREINT );


ALTER TABLE     PERTENECE
ADD CONSTRAINT FK1_PERTENECE 
FOREIGN KEY (CURP) REFERENCES  ARTISTA(CURP);

 

ALTER TABLE     ESTA
ADD CONSTRAINT  FK1_ESTA  
FOREIGN KEY ( CODCAN ) REFERENCES  CANCION(CODCAN);

ALTER TABLE     ESTA
ADD CONSTRAINT FK2_ESTA 
FOREIGN KEY ( NUMREF , ALBUM) REFERENCES  DISCO( NUMREF , ALBUM);

ALTER TABLE     CANCION
ADD CONSTRAINT  FK1_CANCION  
FOREIGN KEY ( CURPC ) REFERENCES  COMPOSITOR( CURPC );


ALTER TABLE     DISCO
ADD CONSTRAINT FK1_DISCO
FOREIGN KEY (DISQUERA,  ORIGEN_DISQUERA) REFERENCES  DISQUERA(DISQUERA, ORIGEN_DISQUERA);
 
ALTER TABLE     DISCO
ADD CONSTRAINT  FK2_DISCO  
FOREIGN KEY ( NOMBREINT ) REFERENCES  INTERPRETE( NOMBREINT );
 

ALTER TABLE     PERTENECE
ADD CONSTRAINT  FK2_PERTENECE  
FOREIGN KEY ( NOMBREINT ) REFERENCES  INTERPRETE( NOMBREINT );

 
ALTER TABLE     CLUB
ADD CONSTRAINT  FK1_CLUB  
FOREIGN KEY ( NOMBREINT ) REFERENCES  INTERPRETE( NOMBREINT );

