--1. Eliminar un compositor  LUQU01041950 ----
DELETE FROM ESTA
WHERE CODCAN='2';

DELETE FROM ESTA
WHERE CODCAN='4';

DELETE FROM CANCION
WHERE CURPC='LUQU01041950';

DELETE FROM COMPOSITOR
WHERE CURPC='LUQU01041950';

----CHECAMOS QUE FUE ELIMINADA-----
Select *
FROM CANCION NATURAL JOIN ESTA
WHERE CURPC='LUQU01041950';



--2. Eliminar un compositor  LUQU01041950 ----
DELETE FROM ESTA
WHERE CODCAN='1';

DELETE FROM ESTA
WHERE CODCAN='3';

DELETE FROM ESTA
WHERE CODCAN='5';

DELETE FROM CANCION
WHERE CURPC='FRSA12091959';

DELETE FROM COMPOSITOR
WHERE CURPC='FRSA12091959';

----CHECAMOS QUE FUE ELIMINADA  FRSA12091959 -----
Select *
FROM CANCION NATURAL JOIN ESTA
WHERE CURPC='FRSA12091959';


--3. Eliminar un compositor  KISA11011960 ----
DELETE FROM ESTA
WHERE CODCAN='15';

DELETE FROM CANCION
WHERE CURPC='KISA11011960';

DELETE FROM COMPOSITOR
WHERE CURPC='KISA11011960';

----CHECAMOS QUE FUE ELIMINADA  KISA11011960-----
Select *
FROM CANCION NATURAL JOIN ESTA
WHERE CURPC='KISA11011960';


---- 4.ELIMINAR DISCO FUEGO--------
DELETE FROM ESTA 
WHERE NUMREF='2';

DELETE FROM DISCO
WHERE NUMREF='2';

---COMPROBAR QUE YA NO EXISTE EL DISCO FUEGO---
SELECT *
FROM DISCO NATURAL JOIN ESTA
WHERE NUMREF='2';


-----5. ELIMINAR DISCO FINISTIERRA-------
DELETE FROM ESTA 
WHERE NUMREF='4';

DELETE FROM DISCO
WHERE NUMREF='4';

---COMPROBAR QUE YA NO EXISTE EL DISCO FUEGO---
SELECT *
FROM DISCO NATURAL JOIN ESTA
WHERE NUMREF='4';


-----6.ELIMINAR DISQUERA EMI Music-------
DELETE FROM DISQUERA
WHERE DISQUERA='EMI Music';

SELECT *
FROM DISQUERA
WHERE DISQUERA='EMI Music';

-----7.ELIMINAR DISQUERA EMI Music-------
DELETE FROM DISQUERA
WHERE DISQUERA='Columbia Records';

SELECT *
FROM DISQUERA
WHERE DISQUERA='Columbia Records';


-----8. Eliminar CLUB Henu--------
DELETE FROM CLUB
WHERE NOMBRE='Henu' AND LUGARORIGEN='Italia';

--Comprobar que CLUB henu fue Eliminado----------
SELECT *
FROM CLUB
WHERE NOMBRE='Henu' AND LUGARORIGEN='Italia';

---- 9. Eliminar Interprete Bond-----------
DELETE FROM CLUB
WHERE NOMBREINT='Bond';

DELETE FROM PERTENECE
WHERE NOMBREINT='Bond';

DELETE FROM INTERPRETE
WHERE NOMBREINT='Bond';

----Comprobar que fue borrado Bond*------
SELECT *
FROM INTERPRETE NATURAL JOIN CLUB NATURAL JOIN PERTENECE
WHERE NOMBREINT='Bond';


-----10. Elimarnar ARTISTA EOCH12232987----------
DELETE
FROM ARTISTA
WHERE CURP='EOCH12232987';
---Comprobar que fue eliminado EOCH12232987-----------
SELECT *
FROM ARTISTA
WHERE CURP='EOCH12232987';



----UPDATE--------
-----1. Actualizar el nombre del artista  Tania Davis a Tania Davis Jil------------
UPDATE ARTISTA
SET NOMBRE='Tania Davis Jil'
WHERE CURP='TADA12031987';


----2. Actualizar la duracion a la cancion VICTORY A 05:00-------

UPDATE CANCION
SET DURACION='05:00'
WHERE COD='7';
---Comprobar que se actualizo----
SELECT *
FROM CANCION
WHERE COD='7';

----3. Actualizar el nombre de la cancion DUEL A DUEL1-------

UPDATE CANCION
SET TITULO='DUEL1'
WHERE COD='9';
---Comprobar que se actualizo----
SELECT *
FROM CANCION
WHERE COD='9';

----4. Actualizar el nombre de la cancion Oceanic A Oceanic2-------

UPDATE CANCION
SET TITULO='Oceanic2'
WHERE COD='8';
---Comprobar que se actualizo----
SELECT *
FROM CANCION
WHERE COD='8';

---5. ACTUALIZAR LA DIRECCION DE LA DISQUERA SonoRodven----
UPDATE DISQUERA
SET DIRECCION='Mexico'
WHERE DISQUERA='SonoRodven';

---COMPROBAR--

SELECT *
FROM DISQUERA
WHERE DISQUERA='SonoRodven';

---6. ACTUALIZAR LA DIRECCION DE LA DISQUERA SonoRodven----
UPDATE DISQUERA
SET DIRECCION='Valley'
WHERE DISQUERA='DGC Records';

---COMPROBAR--

SELECT *
FROM DISQUERA
WHERE DISQUERA='DGC Records';


----7 Aumetar el numero de fan de PXNDX 
UPDATE CLUB
SET NUMFANS='25000'
WHERE NOMBRE='Pxndx' AND LUGARORIGEN LIKE'M%';

Select *
from CLUB
WHERE NOMBRE='Pxndx' AND LUGARORIGEN LIKE'M%';


----8 Aumetar el numero de fan de PXNDX 
UPDATE CLUB
SET NUMFANS='2000'
WHERE NOMBRE='Bboss' AND LUGARORIGEN LIKE'Espa%';

Select *
from CLUB
WHERE NOMBRE='Bboss' AND LUGARORIGEN LIKE'Espa%';


-----9 Cambiar el pais de interprete ---------
UPDATE INTERPRETE
SET PAIS='Espa'
WHERE NOMBREINT='Mago de Oz';

Select *
from INTERPRETE
WHERE NOMBREINT='Mago de Oz';


-----10  Cambiar el genero del Disco   ----------
UPDATE DISCO
SET GENERO='Pop'
WHERE NUMREF='20' AND ALBUM='Fuerza';

SELECT *
FROM DISCO
WHERE NUMREF='20' AND ALBUM='Fuerza';


------Practica 11
-----Total de discos publicados por cada país---
SELECT * FROM DISCO WHERE ORIGEN_DISQUERA='Colombia';

SELECT ORIGEN_DISQUERA AS PAIS, COUNT(NUMREF) AS Total_Discos
FROM DISCO
GROUP BY ORIGEN_DISQUERA;


---Número de canciones por genero-----

SELECT GENERO, COUNT(CODCAN) AS Total_CANCION
FROM DISCO NATURAL INNER JOIN ESTA NATURAL INNER JOIN CANCION
GROUP BY GENERO;


/*Obtener las canciones que tienen el mismo titulo pero que fueron escritas
por diferente compositor*/

SELECT TITULO, COUNT(CURPC) AS NUM_COMPOSITOR
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY TITULO;

---Sleccionar los que tenan mas de un num_compositor---

SELECT TITULO
FROM (
SELECT TITULO, COUNT(CURPC) AS NUM_COMPOSITOR
FROM CANCION NATURAL INNER JOIN COMPOSITOR
GROUP BY TITULO
)
WHERE NUM_COMPOSITOR > 1;






